title: Food Security
title_es: Seguridad Alimentaria
content: As someone who skipped meals because I couldn't afford food, eating ice
  to feel full, I know firsthand how important food security is to health and
  mental well-being. We deserve healthy food for all Denverites.
content_es: Como alguien que se saltó comidas porque no podía costear comida,
  comiendo hielo para sentirme lleno, sé de primera mano lo importante que es la
  seguridad alimentaria para la salud y el bienestar mental. Merecemos alimentos
  saludables para todos los habitantes de Denver.
link: /issues/food-security
lucideIcon: Apple
