title: Food Security
title_es: Seguridad Alimentaria
summary: As someone who skipped meals because I couldn't afford food, eating ice
  to feel full, I know firsthand how important food security is to health and
  mental well-being. We deserve healthy food for all Denverites.
summary_es: Como alguien que se saltó comidas porque no podía costear comida,
  comiendo hielo para sentirme lleno, sé de primera mano lo importante que es la
  seguridad alimentaria para la salud y el bienestar mental. Merecemos alimentos
  saludables para todos los habitantes de Denver.
intro: >-
  1 in 6 people you meet in Denver have eaten less or skipped a meal this year
  because they didn't have enough money for food. Most of them did so multiple
  times throughout the year.\

  \

  Why? The cost of food for the average Denverite is $1,000 every month. At minimum wage, that's **nearly half of your take home pay.**
intro_es: >-
  1 de cada 6 personas que conoces en Denver ha comido menos o se ha saltado una
  comida este año porque no tenía suficiente dinero para comida. La mayoría lo
  hizo varias veces a lo largo del año.\

  \

  ¿Por qué? El costo de la comida para el habitante promedio de Denver es de $1,000 al mes. Con el salario mínimo, eso es **casi la mitad de tu salario neto.**
slug: food-security
lucideIcon: Apple
order: 4
subIssues:
  - summary_es: 2 de cada 3 habitantes de Denver dicen que la comida saludable en
      los supermercados es simplemente demasiado cara. **Comer saludablemente no
      debería ser una práctica reservada para los adinerados.** Si la comida que
      comemos nos está matando, el sistema no funciona.
    title: Food is medicine.
    summary: 2 out of 3 Denverites say that healthy food at grocery stores is just
      too expensive. **Eating healthy shouldn't be a practice reserved for the
      wealthy.** If the food we eat is killing us, the system doesn't work.
    problemsAndSolutions:
      - solution_es: >-
          * • Priorizar árboles y arbustos frutales sobre todos los demás tipos
          en los parques de Denver para crear bosques de alimentos naturales
          alrededor de nuestra ciudad.

          * • Plantar jardines elevados y en tierra en gran parte de los terrenos de nuestros parques urbanos.

          * • Redirigir el empleo en los parques para enfocarse en jardineros, agricultores y horticultores.

          * • Canalizar las cosechas de estos jardines y bosques de alimentos hacia mercados móviles de productos frescos con descuento que visiten las comunidades con mayor inseguridad alimentaria.

          * • Los productos que no cumplen los estándares de calidad se regalan gratuitamente.
        problem: The first corner cut on food is often its healthiness. Meanwhile,
          Denver has nearly 20,000 acres of parkland, almost none of it
          producing a single ounce of food for our 750,000 residents.
        solution: >-
          * • Prioritize fruit-bearing trees and bushes over all other kinds in
          Denver parks to create natural food forests around our city.

          * • Plant raised and in-ground gardens throughout much of the acreage of our city parks.

          * • Shift park employment to focus on gardners, farmers, and horticulturists.

          * • Funnel the harvests of these gardens and food forests to discounted mobile produce markets that visit communities facing the most food insecurity.

          * • Produce that doesn't meet quality standards is given away for free.
        problem_es: Lo primero que se sacrifica en la comida suele ser su valor
          nutritivo. Mientras tanto, Denver tiene casi 20,000 acres de parques,
          casi ninguno de los cuales produce ni una onza de alimento para
          nuestros 750,000 residentes.
    title_es: La comida es medicina.
